
task :env do
  $: << '.' unless $:.include? '.'
  require 'gstar'
  require 'pp'
  require 'base64'
end

desc 'Run Console'
task :console => :env do |t, args|
  puts "Loading #{Ground.env} environment"
  require "irb"
  require 'irb/completion'
  ARGV.clear
  IRB.start
end

namespace :maintain do
  task :pull_stars_from_github => :env do
    page = 0
    loop do
      page += 1
      res = GithubAPI::ListStarredRepos(page: page)
      stars = JSON.parse res
      stars.each {|star|
        pulled_star = Gstar::DB[:stars].where(source_id: "github_#{star['id']}").first
        if pulled_star.nil?
          InsertStarFromGithub star
        end
      }
      puts page
      break if stars.size == 0
    end
   end

  task :sync_stars_from_github => :env do
    res = GithubAPI::ListStarredRepos()
    stars = JSON.parse res
    stars.each {|star|
      pulled_star = Gstar::DB[:stars].where(source_id: "github_#{star['id']}").first
      if pulled_star.nil?
        puts "sync the star #{star['full_name']}..."
        InsertStarFromGithub star
      end
    }
  end

  desc 'build full text serach index'
  task :build_full_text_index => :env do
    Gstar::DB[:stars].each {|star|
      BuildInvertedStarIndex(star: star)
    }
  end
   
end

namespace :debug do
  task :list_starred_repos => :env do
    res = GithubAPI::ListStarredRepos()
    res = JSON.parse res
    pp res
    pp res.size
  end
end

namespace :db do
  task :migrate => :env do
    Sequel.extension :migration, :core_extensions
    Sequel::Migrator.run Gstar::DB, 'db/migrations', use_transactions: true
  end
end

